version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  python:
    executor:
      name: python/default
      tag: "3.9"
    steps:
      - checkout
      - run: pip install cookiecutter
      - run: cookiecutter . --no-input
      - run: pip install -e./wagtail-localize[testing]
      - run: cd wagtail-localize && python testmanage.py test

workflows:
  main:
    jobs:
      - python
